import pygame
from enum inport Enum, auto
from dataclasses import dataclass

## dependencies should be provided by teammates
## these are just minimal interfaces for main and everyone else should match them in their files

class Player:
  def input_handling(self, events): ...
  def update(self, dt, world): ...
  def draw(self, surf) ...
  @property 
  def on_edge(self) -> bool: ...
  @property
  def is_pushing(self) -> bool: ...
  @property
  def trail(self) -> list[tuple[int, int]]: ...
  def reset_after_hit(self): ...
  def start(self): ... 
  def stop(self): ... 
  @property
  def push_start_cell(self) -> tuple[int, int] ...
  @property
  def cell(self) -> tuple[int, int]: ... 
    
class Qix:
  def update(self, dt, world): ... 
  def draw(self, surf): ... 
  @property
  def cell(self) -> tuplr[int, int]: ... 

class SparxManager:
  def update(self, dt, world): ... 
  def draw(self, surf): ...
  def hits_player(self, player_cell) -> bool: ... 
  def hit_push_start(self, push_start_cell) -> bool: ...

#grid and rules
class world:
  tile_size: int
  width_size: int 
  height_tiles: int

  def draw(self, surf): ... 
  def reset_push(self): ... 
  def apply_trail(self, trail: list[tuple[int, int]]): ... 
  def seal_area(self, qix_cell, trail) -> None: ...
  def percent_claimed(self) -> float: ... 
  def qix_hits_trail(self, qix_cell, trail) -> bool: ... 
  def rebuild_boundry(self): ... 
    





  
